/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lwlee' at '3/25/17 9:26 PM' with Gradle 2.14.1
 *
 * @author lwlee, @date 3/25/17 9:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
